# CodeRabbit 설정 파일
# 코드 리뷰를 한국어로 받기 위한 설정

# 언어 설정
language: ko

# 리뷰 설정
reviews:
  # 한국어로 응답
  response_language: ko
  # 상세한 리뷰 활성화
  thoroughness: high
  # 건설적인 피드백 활성화
  tone: polite

# 명령어 설정 (PR 코멘트에서 사용)
# @coderabbitai please respond in Korean
# 위와 같이 PR에 코멘트를 남기면 한국어로 응답을 요청할 수 있습니다

